baseURL = "https://github.com/Frederik-N-H-Lundgren/frederik-n-h-lundgren.github.io"
title = "Buy Stuff for your pet!!"
description = "This is a project description"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Fredeirk Lundgren", "Weinan Xiong"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/Frederik-N-H-Lundgren/frederik-n-h-lundgren.github.io"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

