baseURL = "https://Frederik-N-H-Lundgren.github.io/frederik-n-h-lundgren.github.io"
title = "Co-purchases of pet supply items!"
description = "This is a project description"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Fredeirk Lundgren", "Weinan Xiong"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com/drive/folders/16yvSK5YmO1NO6kwBjXCla8SDcDmi7hDN?usp=sharing"
    github = "https://github.com/Frederik-N-H-Lundgren/frederik-n-h-lundgren.github.io"
    [[params.nav]]
        label = "Community"
        link = "/data-description"
    [[params.nav]]
        label = "Fun Facts"
        link = "/network-analysis"
    [[params.nav]]
        label = "Surprise"
        link = "/text-analysis"

